version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    restart: always
    container_name: xxl-job-admin
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://IP:PORT/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=xxx --spring.datasource.password=xxx --xxl.job.accessToken=xxx'
    ports:
      - 9001:8080
    volumes:
      - ./data/applogs:/data/applogs