version: '3.1'
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/usr/share/nginx/app
      - ./cert:/etc/nginx/cert
      - ./log:/var/log/nginx
